import { createClient } from "@/lib/supabase/server";

export type EventCardData = { id: string; title: string; description: string; category: string; starts_at: string; location_name: string; public_address: string; kind: string; organizer_id: string | null; organizer: { username: string; display_name: string } | null; photo_url: string | null; interest_count: number; interested: boolean };
type RawEvent = { id: string; title: string; description: string; category: string; starts_at: string; location_name: string; public_address: string; kind: string; organizer_id: string | null; photo_path: string | null };

export async function getEvents(timeFilter: string, category: string, page: number) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { events: [] as EventCardData[], hasMore: false }; const { data: rows, error } = await supabase.rpc("list_upcoming_events", { time_filter: timeFilter, category_filter: category, result_limit: 21, result_offset: page * 20 }); if (error) throw error; const typedRows = (rows ?? []) as RawEvent[]; const visible = typedRows.slice(0, 20); const ids = visible.map((event) => event.id); const organizerIds = [...new Set(visible.map((event) => event.organizer_id).filter(Boolean))] as string[];
  const [{ data: organizers }, { data: interests }] = await Promise.all([organizerIds.length ? supabase.from("profiles").select("id, username, display_name").in("id", organizerIds) : { data: [] }, ids.length ? supabase.from("event_interests").select("event_id, user_id").in("event_id", ids) : { data: [] }]); const organizerMap = new Map((organizers ?? []).map((profile) => [profile.id, profile])); const interestCount = new Map<string, number>(); const mine = new Set<string>(); (interests ?? []).forEach((item) => { interestCount.set(item.event_id, (interestCount.get(item.event_id) ?? 0) + 1); if (item.user_id === user.id) mine.add(item.event_id); }); const paths = visible.map((event) => event.photo_path).filter(Boolean) as string[]; const { data: urls } = paths.length ? await supabase.storage.from("event-media").createSignedUrls(paths, 3600) : { data: [] }; const urlMap = new Map((urls ?? []).map((item) => [item.path, item.signedUrl]));
  return { events: visible.map((event): EventCardData => ({ id: event.id, title: event.title, description: event.description, category: event.category, starts_at: event.starts_at, location_name: event.location_name, public_address: event.public_address, kind: event.kind, organizer_id: event.organizer_id, organizer: event.organizer_id ? organizerMap.get(event.organizer_id) ?? null : null, photo_url: event.photo_path ? urlMap.get(event.photo_path) ?? null : null, interest_count: interestCount.get(event.id) ?? 0, interested: mine.has(event.id) })), hasMore: typedRows.length > 20 };
}
