import Link from "next/link";
import { markNotificationsRead } from "@/app/actions/messaging";
import { createClient } from "@/lib/supabase/server";

const labels: Record<string, string> = { follow: "a început să te urmărească", follow_request: "ți-a trimis o cerere de urmărire", follow_accepted: "ți-a acceptat cererea de urmărire", like: "a apreciat postarea ta", comment: "a comentat la postarea ta", event_interest: "este interesat(ă) de ieșirea ta", message_request: "ți-a trimis o cerere de conversație", message: "ți-a trimis un mesaj" };
export const metadata = { title: "Notificări" };
export default async function NotificationsPage() { const supabase = await createClient(); const { data: notifications } = await supabase.from("notifications").select("id, actor_id, type, entity_id, read_at, created_at").order("created_at", { ascending: false }).limit(100); const actorIds = [...new Set((notifications ?? []).map((item) => item.actor_id).filter(Boolean))] as string[]; const { data: actors } = actorIds.length ? await supabase.from("profiles").select("id, username, display_name").in("id", actorIds) : { data: [] }; const actorMap = new Map((actors ?? []).map((item) => [item.id, item])); function href(type: string, entity: string | null, actorId: string | null) { if (["follow", "follow_request", "follow_accepted"].includes(type)) { const actor = actorId ? actorMap.get(actorId) : null; return actor ? `/profil/${actor.username}` : "/profil"; } if (["like", "comment"].includes(type)) return `/postare/${entity}`; if (type === "event_interest") return `/iesim/${entity}`; if (["message", "message_request"].includes(type)) return `/mesaje/${entity}`; return "/notificari"; }
  return <><div className="flex items-end justify-between gap-3"><div><p className="text-sm font-semibold text-violet-300">Activitate</p><h1 className="mt-1 text-3xl font-black">Notificări</h1></div><form action={markNotificationsRead}><button className="text-sm font-semibold text-violet-300">Marchează toate citite</button></form></div><div className="mt-7 space-y-2">{notifications?.map((notification) => { const actor = notification.actor_id ? actorMap.get(notification.actor_id) : null; return <Link href={href(notification.type, notification.entity_id, notification.actor_id)} key={notification.id} className={`flex gap-3 rounded-2xl border p-4 ${notification.read_at ? "border-white/6 bg-white/[.025]" : "border-violet-400/20 bg-violet-400/[.07]"}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-violet-500/15 font-bold text-violet-200">{actor?.display_name[0]?.toUpperCase() ?? "P"}</div><div><p className="text-sm"><b>{actor?.display_name ?? "PitVibe.ro"}</b> {labels[notification.type] ?? "are activitate nouă"}.</p><time className="mt-1 block text-xs text-[#827b8e]">{new Intl.DateTimeFormat("ro-RO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(notification.created_at))}</time></div></Link>; })}{!notifications?.length && <div className="card p-10 text-center text-[#918a9e]">Nu ai notificări încă.</div>}</div></>;
}
