import Link from "next/link";
import { markNotificationsRead } from "@/app/actions/messaging";
import { respondGesture } from "@/app/actions/social";
import { createClient } from "@/lib/supabase/server";

const labels: Record<string, string> = { follow: "a început să te urmărească", follow_request: "ți-a trimis o cerere de urmărire", follow_accepted: "ți-a acceptat cererea de urmărire", like: "a apreciat postarea ta", comment: "a comentat la postarea ta", event_interest: "este interesat(ă) de ieșirea ta", message_request: "ți-a trimis o cerere de conversație", message: "ți-a trimis un mesaj" };
function notificationLabel(type: string, senderGender?: string | null, recipientGender?: string | null) { if (type === "gesture") return senderGender === "male" && recipientGender === "female" ? "ți-a trimis un trandafir" : senderGender === "female" && recipientGender === "male" ? "ți-a trimis o scânteie" : "ți-a trimis un gest"; return labels[type] ?? "are activitate nouă"; }
export const metadata = { title: "Notificări" };

export default async function NotificationsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (user) await supabase.from("notifications").update({ read_at: new Date().toISOString() }).eq("recipient_id", user.id).is("read_at", null);
  const { data: recipient } = user ? await supabase.from("profiles").select("gender").eq("id", user.id).maybeSingle() : { data: null };
  const { data: notifications } = await supabase.from("notifications").select("id, actor_id, type, entity_id, read_at, created_at").order("created_at", { ascending: false }).limit(100);
  const actorIds = [...new Set((notifications ?? []).map((item) => item.actor_id).filter(Boolean))] as string[];
  const { data: actors } = actorIds.length ? await supabase.from("profiles").select("id, username, display_name, gender").in("id", actorIds) : { data: [] };
  const actorMap = new Map((actors ?? []).map((item) => [item.id, item]));
  const { data: matches } = user ? await supabase.from("profile_matches").select("user_one, user_two").or(`user_one.eq.${user.id},user_two.eq.${user.id}`) : { data: [] };
  const matchedIds = new Set((matches ?? []).map((match) => match.user_one === user?.id ? match.user_two : match.user_one));
  function href(type: string, entity: string | null, actorId: string | null) { if (["follow", "follow_request", "follow_accepted", "gesture"].includes(type)) { const actor = actorId ? actorMap.get(actorId) : null; return actor ? `/profil/${actor.username}` : "/profil"; } if (["like", "comment"].includes(type)) return `/postare/${entity}`; if (type === "event_interest") return `/iesim/${entity}`; if (["message", "message_request"].includes(type)) return `/mesaje/${entity}`; return "/notificari"; }
  return <><div className="flex items-end justify-between gap-3"><div><p className="text-sm font-semibold text-violet-300">Activitate</p><h1 className="mt-1 text-3xl font-black">Notificări</h1></div><form action={markNotificationsRead}><button className="text-sm font-semibold text-violet-300">Marchează toate citite</button></form></div><div className="mt-7 space-y-2">{notifications?.map((notification) => { const actor = notification.actor_id ? actorMap.get(notification.actor_id) : null; const isGesture = notification.type === "gesture"; const isMatched = actor ? matchedIds.has(actor.id) : false; return <div key={notification.id} className={`flex gap-3 rounded-2xl border p-4 ${notification.read_at ? "border-white/6 bg-white/[.025]" : "border-violet-400/20 bg-violet-400/[.07]"}`}><Link href={href(notification.type, notification.entity_id, notification.actor_id)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-violet-500/15 font-bold text-violet-200">{actor?.display_name[0]?.toUpperCase() ?? "P"}</Link><div className="min-w-0 flex-1"><p className="text-sm"><b>{actor?.display_name ?? "PitVibe.ro"}</b> {notificationLabel(notification.type, actor?.gender, recipient?.gender)}.</p><time className="mt-1 block text-xs text-[#827b8e]">{new Intl.DateTimeFormat("ro-RO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(notification.created_at))}</time>{isGesture && actor && !isMatched && <div className="mt-3 flex gap-2"><form action={respondGesture}><input type="hidden" name="sender_id" value={actor.id} /><input type="hidden" name="decizie" value="accept" /><button className="button-primary min-h-9 px-3 text-xs">Apreciez</button></form><form action={respondGesture}><input type="hidden" name="sender_id" value={actor.id} /><input type="hidden" name="decizie" value="reject" /><button className="button-secondary min-h-9 px-3 text-xs">Nu acum</button></form></div>}{isGesture && isMatched && <Link href="/mesaje" className="button-secondary mt-3 min-h-9 px-3 text-xs">Deschide mesajele</Link>}</div></div>; })}{!notifications?.length && <div className="card p-10 text-center text-[#918a9e]">Nu ai notificări încă.</div>}</div></>;
}
