"use client";
/* Blob previews and private signed URLs are not passed through the public image optimizer. */
/* eslint-disable @next/next/no-img-element */

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";

export function AvatarUploader({ currentUrl, name }: { currentUrl: string | null; name: string }) {
  const input = useRef<HTMLInputElement>(null); const router = useRouter(); const [preview, setPreview] = useState(currentUrl); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function upload(file?: File) { if (!file) return; setBusy(true); setError(""); try { if (!file.type.startsWith("image/") || file.size > 10 * 1024 * 1024) throw new Error("Alege o imagine de maximum 10 MB."); const bitmap = await createImageBitmap(file); const canvas = document.createElement("canvas"); canvas.width = 640; canvas.height = 640; const context = canvas.getContext("2d"); if (!context) throw new Error("Imaginea nu poate fi procesată."); const size = Math.min(bitmap.width, bitmap.height); context.drawImage(bitmap, (bitmap.width - size) / 2, (bitmap.height - size) / 2, size, size, 0, 0, 640, 640); bitmap.close(); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/webp", .84)); if (!blob) throw new Error("Imaginea nu poate fi procesată."); const form = new FormData(); form.set("avatar", new File([blob], "avatar.webp", { type: "image/webp" })); const response = await fetch("/api/avatar", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setPreview(URL.createObjectURL(blob)); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Încărcarea a eșuat."); } finally { setBusy(false); } }
  return <div><div className="flex items-center gap-5"><div className="h-24 w-24 overflow-hidden rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500">{preview ? <img src={preview} alt={`Fotografia de profil a lui ${name}`} className="h-full w-full object-cover" /> : <span className="grid h-full place-items-center text-3xl font-bold">{name[0]?.toUpperCase()}</span>}</div><div><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => upload(event.target.files?.[0])} /><button className="button-secondary" type="button" disabled={busy} onClick={() => input.current?.click()}>{busy ? "Se încarcă…" : "Schimbă fotografia"}</button><p className="mt-2 text-xs text-[#827b8e]">Decupare pătrată, maximum 10 MB.</p></div></div>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}</div>;
}
