"use client";
/* Previzualizarea folosește un Blob local, iar fotografia finală este optimizată la încărcare. */
/* eslint-disable @next/next/no-img-element */

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";

export function EventComposer({ places }: { places: { id: string; name: string; public_address: string }[] }) {
  const router = useRouter(); const fileInput = useRef<HTMLInputElement>(null); const [image, setImage] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function choose(file?: File) { if (!file) return; try { if (!file.type.startsWith("image/") || file.size > 15 * 1024 * 1024) throw new Error("Alege o imagine de maximum 15 MB."); const bitmap = await createImageBitmap(file); const scale = Math.min(1, 1600 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement("canvas"); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale); canvas.getContext("2d")?.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close(); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/webp", .82)); if (!blob || blob.size > 2 * 1024 * 1024) throw new Error("Imaginea rămâne prea mare după comprimare."); setImage(new File([blob], "cover.webp", { type: "image/webp" })); setPreview(URL.createObjectURL(blob)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Imaginea nu poate fi procesată."); } }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!navigator.onLine) { setError("Ești offline. Ieșirea nu a fost trimisă."); return; } setBusy(true); setError(""); const form = new FormData(event.currentTarget); const localDate = String(form.get("date_local") ?? ""); const parsed = new Date(localDate); if (Number.isNaN(parsed.getTime())) { setError("Alege data și ora."); setBusy(false); return; } form.delete("date_local"); form.set("starts_at", parsed.toISOString()); if (image) form.set("image", image); try { const response = await fetch("/api/events", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error); router.push(`/iesim/${result.id}`); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Ieșirea nu a putut fi creată."); setBusy(false); } }
  return <form onSubmit={submit} className="card space-y-5 p-6"><label className="block"><span className="mb-2 block text-sm font-semibold">Titlu</span><input className="field" name="title" minLength={3} maxLength={120} required placeholder="Ex: Cafea și povești în centru" /></label><label className="block"><span className="mb-2 block text-sm font-semibold">Descriere</span><textarea className="field min-h-32 resize-y" name="description" maxLength={2000} placeholder="Spune pe scurt ce ai în plan și cui i-ar plăcea." /></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Categorie</span><select className="field" name="category" required><option value="cafea">Cafea</option><option value="sport">Sport</option><option value="plimbare">Plimbare</option><option value="muzica">Muzică</option><option value="socializare">Socializare</option></select></label><label><span className="mb-2 block text-sm font-semibold">Data și ora</span><input className="field [color-scheme:dark]" name="date_local" type="datetime-local" required /></label></div>{places.length > 0 && <label className="block"><span className="mb-2 block text-sm font-semibold">Loc din catalog <span className="font-normal text-[#827b8e]">(opțional)</span></span><select className="field" name="place_id" defaultValue=""><option value="">Alt loc</option>{places.map((place) => <option value={place.id} key={place.id}>{place.name} — {place.public_address}</option>)}</select></label>}<div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Numele locului</span><input className="field" name="location_name" minLength={2} maxLength={120} required placeholder="Ex: Piața Primăriei" /></label><label><span className="mb-2 block text-sm font-semibold">Adresă publică <span className="font-normal text-[#827b8e]">(opțional)</span></span><input className="field" name="address" maxLength={200} placeholder="Fără locație GPS în timp real" /></label></div><div><input ref={fileInput} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => choose(event.target.files?.[0])} /><button className="button-secondary" type="button" onClick={() => fileInput.current?.click()}>{image ? "Schimbă fotografia" : "Adaugă o fotografie"}</button>{preview && <div className="mt-3 aspect-[16/9] overflow-hidden rounded-2xl"><img src={preview} alt="Previzualizarea ieșirii" className="h-full w-full object-cover" /></div>}</div>{error && <p role="alert" className="rounded-xl bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>}<button className="button-primary w-full" disabled={busy} type="submit">{busy ? "Se publică…" : "Publică ieșirea"}</button><p className="text-xs leading-5 text-[#827b8e]">„Mă interesează” nu reprezintă rezervare, bilet sau participare confirmată.</p></form>;
}
