import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: Request) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ error: "Autentificare necesară." }, { status: 401 }); const form = await request.formData();
  const title = String(form.get("title") ?? "").trim(); const description = String(form.get("description") ?? "").trim(); const category = String(form.get("category") ?? ""); const locationName = String(form.get("location_name") ?? "").trim(); const address = String(form.get("address") ?? "").trim(); const startsAt = new Date(String(form.get("starts_at") ?? "")); const placeId = String(form.get("place_id") ?? "") || null; const categories = new Set(["cafea", "sport", "plimbare", "muzica", "socializare"]);
  if (title.length < 3 || title.length > 120 || description.length > 2000 || !categories.has(category) || locationName.length < 2 || locationName.length > 120 || address.length > 200 || Number.isNaN(startsAt.getTime()) || startsAt <= new Date()) return NextResponse.json({ error: "Verifică titlul, locul și data viitoare a ieșirii." }, { status: 400 });
  const eventId = crypto.randomUUID(); const image = form.get("image"); let photoPath: string | null = null;
  if (image instanceof File && image.size > 0) { if (image.size > 2 * 1024 * 1024 || image.type !== "image/webp") return NextResponse.json({ error: "Fotografia trebuie să fie WebP și să aibă maximum 2 MB." }, { status: 400 }); const bytes = new Uint8Array(await image.arrayBuffer()); if (String.fromCharCode(...bytes.slice(0, 4)) !== "RIFF" || String.fromCharCode(...bytes.slice(8, 12)) !== "WEBP") return NextResponse.json({ error: "Fotografia nu este validă." }, { status: 400 }); photoPath = `${user.id}/${eventId}/cover.webp`; const { error } = await supabase.storage.from("event-media").upload(photoPath, bytes, { contentType: "image/webp" }); if (error) return NextResponse.json({ error: "Fotografia nu a putut fi încărcată." }, { status: 500 }); }
  const { error } = await supabase.from("events").insert({ id: eventId, kind: "outing", organizer_id: user.id, title, description, category, starts_at: startsAt.toISOString(), place_id: placeId, location_name: locationName, public_address: address, photo_path: photoPath }); if (error) { if (photoPath) await supabase.storage.from("event-media").remove([photoPath]); return NextResponse.json({ error: "Ieșirea nu a putut fi creată." }, { status: 500 }); }
  return NextResponse.json({ id: eventId }, { status: 201 });
}
