/* Fotografiile private folosesc URL-uri semnate cu durată limitată. */
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { notFound } from "next/navigation";
import { deleteEvent, toggleEventInterest } from "@/app/actions/social";
import { createClient } from "@/lib/supabase/server";

const labels: Record<string, string> = { cafea: "Cafea", sport: "Sport", plimbare: "Plimbare", muzica: "Muzică", socializare: "Socializare" };
export default async function EventPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { data: event } = await supabase.from("events").select("id, title, description, category, starts_at, ends_at, location_name, public_address, photo_path, organizer_id, kind, status, profiles!events_organizer_id_fkey(username, display_name), places(name, public_address)").eq("id", id).single(); if (!event || !user) notFound(); const [{ count }, { data: mine }, { data: photo }] = await Promise.all([supabase.from("event_interests").select("event_id", { count: "exact", head: true }).eq("event_id", id), supabase.from("event_interests").select("event_id").eq("event_id", id).eq("user_id", user.id).maybeSingle(), event.photo_path ? supabase.storage.from("event-media").createSignedUrl(event.photo_path, 3600) : Promise.resolve({ data: null })]); const organizer = event.profiles[0]; const date = new Intl.DateTimeFormat("ro-RO", { timeZone: "Europe/Bucharest", dateStyle: "full", timeStyle: "short" }).format(new Date(event.starts_at)); const past = new Date(event.starts_at) <= new Date();
  return <><article className="card overflow-hidden">{photo?.signedUrl && <img className="max-h-[520px] w-full object-cover" src={photo.signedUrl} alt={`Imagine pentru ${event.title}`} />}<div className="p-6 sm:p-8"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-violet-400/10 px-3 py-1 text-xs font-bold text-violet-200">{labels[event.category]}</span>{event.kind === "local_event" && <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-200">Eveniment local</span>}{past && <span className="rounded-full bg-white/7 px-3 py-1 text-xs text-[#aaa4b8]">Încheiat</span>}</div><h1 className="mt-5 text-3xl font-black tracking-[-.04em] sm:text-4xl">{event.title}</h1><p className="mt-4 font-semibold text-fuchsia-200">{date}</p><p className="mt-2 text-[#aaa4b8]">{event.location_name}{event.public_address ? ` · ${event.public_address}` : ""}</p>{event.description && <p className="mt-6 whitespace-pre-wrap leading-7 text-[#ddd7e5]">{event.description}</p>}<div className="mt-6 border-t border-white/8 pt-5 text-sm text-[#918a9e]">{organizer ? <>Organizat de <Link className="font-semibold text-violet-300" href={`/profil/${organizer.username}`}>{organizer.display_name}</Link></> : "Eveniment local"} · {count ?? 0} persoane interesate</div>{!past && event.status === "active" && <form action={toggleEventInterest} className="mt-6"><input type="hidden" name="event_id" value={id} /><button className={mine ? "button-secondary" : "button-primary"}>{mine ? "Retrage interesul" : "Mă interesează"}</button></form>}<div className="mt-4 flex justify-between gap-3 text-xs text-[#827b8e]"><p>Exprimarea interesului nu reprezintă rezervare, bilet sau participare confirmată.</p>{event.organizer_id !== user.id && <Link className="text-red-300" href={`/raporteaza/event/${id}?return=/iesim/${id}`}>Raportează</Link>}</div></div></article>{event.organizer_id === user.id && <section className="mt-5 rounded-3xl border border-red-400/20 bg-red-400/[.045] p-6"><h2 className="font-bold text-red-200">Gestionează ieșirea</h2><p className="mt-2 text-sm text-[#aaa4b8]">Ștergerea elimină ieșirea și toate exprimările de interes.</p><form action={deleteEvent} className="mt-4"><input type="hidden" name="event_id" value={id} /><button className="rounded-full bg-red-500 px-5 py-3 font-bold text-white">Șterge ieșirea</button></form></section>}</>;
}
