import Link from "next/link";
import { respondConversation } from "@/app/actions/messaging";
import { createClient } from "@/lib/supabase/server";

export const metadata = { title: "Mesaje" };
type MessagePreview = { conversation_id: string; content: string; created_at: string; sender_id: string };
export default async function MessagesPage() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { data: conversations } = await supabase.from("conversations").select("id, requester_id, recipient_id, status, updated_at").or(`requester_id.eq.${user!.id},recipient_id.eq.${user!.id}`).neq("status", "rejected").order("updated_at", { ascending: false }).limit(50); const otherIds = [...new Set((conversations ?? []).map((item) => item.requester_id === user!.id ? item.recipient_id : item.requester_id))]; const [{ data: profiles }, { data: messages }] = await Promise.all([otherIds.length ? supabase.from("profiles").select("id, username, display_name").in("id", otherIds) : { data: [] }, conversations?.length ? supabase.from("messages").select("conversation_id, content, created_at, sender_id").in("conversation_id", conversations.map((item) => item.id)).order("created_at", { ascending: false }).limit(200) : { data: [] }]); const profileMap = new Map((profiles ?? []).map((item) => [item.id, item])); const latest = new Map<string, MessagePreview>(); ((messages ?? []) as MessagePreview[]).forEach((message) => { if (!latest.has(message.conversation_id)) latest.set(message.conversation_id, message); });
  return <><p className="text-sm font-semibold text-violet-300">Conversații private</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em]">Mesaje</h1><p className="mt-3 text-sm text-[#918a9e]">Un prim mesaj este trimis ca cerere. Conversația continuă numai după acceptare.</p><div className="mt-7 space-y-3">{conversations?.map((conversation) => { const incoming = conversation.recipient_id === user!.id && conversation.status === "requested"; const otherId = conversation.requester_id === user!.id ? conversation.recipient_id : conversation.requester_id; const other = profileMap.get(otherId); const last = latest.get(conversation.id); if (!other) return null; return <article className="card p-5" key={conversation.id}><div className="flex items-center gap-3"><Link className="min-w-0 flex-1" href={`/mesaje/${conversation.id}`}><p className="truncate font-bold">{other.display_name}</p><p className="truncate text-xs text-[#827b8e]">@{other.username}</p>{last && <p className="mt-2 truncate text-sm text-[#aaa4b8]">{last.sender_id === user!.id ? "Tu: " : ""}{last.content}</p>}</Link>{incoming ? <div className="flex gap-2"><form action={respondConversation}><input type="hidden" name="conversation_id" value={conversation.id} /><input type="hidden" name="decizie" value="reject" /><button className="button-secondary min-h-10 px-3 text-xs">Refuză</button></form><form action={respondConversation}><input type="hidden" name="conversation_id" value={conversation.id} /><input type="hidden" name="decizie" value="accept" /><button className="button-primary min-h-10 px-3 text-xs">Acceptă</button></form></div> : conversation.status === "requested" ? <span className="rounded-full bg-white/7 px-3 py-1 text-xs text-[#918a9e]">În așteptare</span> : <Link className="text-sm font-bold text-violet-300" href={`/mesaje/${conversation.id}`}>Deschide</Link>}</div></article>; })}{!conversations?.length && <div className="card p-10 text-center"><p className="text-2xl">✉</p><h2 className="mt-3 font-bold">Nicio conversație</h2><p className="mt-2 text-sm text-[#918a9e]">Descoperă o persoană și trimite-i un prim mesaj respectuos.</p><Link className="button-primary mt-6" href="/descopera">Descoperă oameni</Link></div>}</div></>;
}
