import { createClient } from "@/lib/supabase/server";
import { deleteAccount, signOut, updatePrivacy } from "../../autentificare/actions";
import { FormMessage } from "@/components/form-message";

export const metadata = { title: "Setări" };
export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ eroare?: string; mesaj?: string }> }) {
  const params = await searchParams; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { data: profile } = await supabase.from("profiles").select("visibility").eq("id", user!.id).single();
  return <><p className="text-sm font-semibold text-violet-300">Contul tău</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em]">Setări</h1><div className="mt-7"><FormMessage error={params.eroare} message={params.mesaj} /></div><section className="card mt-5 p-6"><h2 className="text-lg font-bold">Confidențialitate</h2><p className="mt-2 text-sm leading-6 text-[#aaa4b8]">Conturile private aprobă fiecare urmăritor înainte ca acesta să vadă conținutul privat.</p><form action={updatePrivacy} className="mt-5 flex flex-col gap-4 sm:flex-row"><select className="field sm:max-w-xs" name="vizibilitate" defaultValue={profile?.visibility ?? "public"}><option value="public">Profil public</option><option value="private">Profil privat</option></select><button className="button-primary" type="submit">Salvează</button></form></section><section className="card mt-5 p-6"><h2 className="text-lg font-bold">Sesiune</h2><p className="mt-2 text-sm text-[#aaa4b8]">Autentificat ca {user?.email}</p><form action={signOut} className="mt-5"><button className="button-secondary" type="submit">Deconectează-te</button></form></section><section className="mt-5 rounded-3xl border border-red-400/20 bg-red-400/[.045] p-6"><h2 className="text-lg font-bold text-red-200">Șterge contul</h2><p className="mt-2 text-sm leading-6 text-[#b9b3c5]">Acțiunea șterge definitiv contul și datele asociate prin regulile bazei de date. Scrie ȘTERGE pentru confirmare.</p><form action={deleteAccount} className="mt-5 flex flex-col gap-4 sm:flex-row"><input className="field sm:max-w-xs" name="confirmare" aria-label="Confirmarea ștergerii" autoComplete="off" required /><button className="inline-flex min-h-12 items-center justify-center rounded-full bg-red-500 px-5 font-bold text-white" type="submit">Șterge definitiv</button></form></section></>;
}
