-- Zone locale cu prezență declarată și temporară.
create table public.local_zones (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null unique check (char_length(name) between 2 and 60),
  description text not null default '' check (char_length(description) <= 160),
  sort_order integer not null default 0,
  active boolean not null default true
);

create table public.zone_checkins (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  zone_id bigint not null references public.local_zones(id) on delete cascade,
  checked_in_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  constraint zone_checkin_lifetime check (expires_at > checked_in_at and expires_at <= checked_in_at + interval '2 hours 5 minutes')
);

create index zone_checkins_active_idx on public.zone_checkins(zone_id, expires_at desc);

insert into public.local_zones(slug, name, description, sort_order) values
  ('stadion', 'Stadion', 'Zona stadionului Nicolae Dobrin', 10),
  ('leroy-merlin', 'Leroy Merlin', 'Zona comercială din nordul orașului', 20),
  ('lunca', 'Lunca', 'Lunca Argeșului și împrejurimi', 30),
  ('strand', 'Ștrand', 'Parcul Ștrand și zona de agrement', 40);

alter table public.local_zones enable row level security;
alter table public.zone_checkins enable row level security;
create policy "zones_read_active" on public.local_zones for select to authenticated using (active);
create policy "zone_checkins_read_self" on public.zone_checkins for select to authenticated using (user_id = auth.uid());
create policy "zone_checkins_create_self" on public.zone_checkins for insert to authenticated with check (user_id = auth.uid() and public.is_active_user());
create policy "zone_checkins_update_self" on public.zone_checkins for update to authenticated using (user_id = auth.uid() and public.is_active_user()) with check (user_id = auth.uid() and public.is_active_user());
create policy "zone_checkins_delete_self" on public.zone_checkins for delete to authenticated using (user_id = auth.uid());

create or replace function public.list_zone_activity()
returns table(id bigint, slug text, name text, description text, people_count bigint, selected boolean)
language sql stable security definer set search_path = '' as $$
  select z.id, z.slug, z.name, z.description,
    count(c.user_id) filter (where c.expires_at > now()) as people_count,
    exists(select 1 from public.zone_checkins mine where mine.user_id = auth.uid() and mine.zone_id = z.id and mine.expires_at > now()) as selected
  from public.local_zones z
  left join public.zone_checkins c on c.zone_id = z.id
  where z.active and auth.uid() is not null
  group by z.id, z.slug, z.name, z.description, z.sort_order
  order by z.sort_order, z.name;
$$;

create or replace function public.check_in_zone(target_zone bigint) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not public.is_active_user() or not exists(select 1 from public.local_zones where id = target_zone and active) then
    raise exception 'Zona nu este disponibilă';
  end if;
  insert into public.zone_checkins(user_id, zone_id, checked_in_at, expires_at)
  values(auth.uid(), target_zone, now(), now() + interval '2 hours')
  on conflict (user_id) do update set zone_id = excluded.zone_id, checked_in_at = excluded.checked_in_at, expires_at = excluded.expires_at;
end;
$$;

create or replace function public.leave_zone() returns void
language sql security definer set search_path = '' as $$
  delete from public.zone_checkins where user_id = auth.uid();
$$;

revoke all on function public.list_zone_activity() from public;
revoke all on function public.check_in_zone(bigint) from public;
revoke all on function public.leave_zone() from public;
grant execute on function public.list_zone_activity() to authenticated;
grant execute on function public.check_in_zone(bigint) to authenticated;
grant execute on function public.leave_zone() to authenticated;
