/* Fotografiile catalogului folosesc URL-uri semnate. */
/* eslint-disable @next/next/no-img-element */
import { createClient } from "@/lib/supabase/server";

const labels: Record<string, string> = { cafea: "Cafea", sport: "Sport", plimbare: "Plimbare", muzica: "Muzică", socializare: "Socializare" };
export const metadata = { title: "Locuri din Pitești" };
export default async function PlacesPage({ searchParams }: { searchParams: Promise<{ categorie?: string }> }) { const params = await searchParams; const category = ["cafea", "sport", "plimbare", "muzica", "socializare"].includes(params.categorie ?? "") ? params.categorie! : ""; const supabase = await createClient(); let query = supabase.from("places").select("id, name, category, description, public_address, photo_path").eq("active", true).order("name").limit(50); if (category) query = query.eq("category", category); const { data: places } = await query; const paths = places?.map((place) => place.photo_path).filter(Boolean) as string[] | undefined; const { data: urls } = paths?.length ? await supabase.storage.from("event-media").createSignedUrls(paths, 3600) : { data: [] }; const urlMap = new Map((urls ?? []).map((item) => [item.path, item.signedUrl]));
  return <><p className="text-sm font-semibold text-violet-300">Catalog local</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em]">Locuri din Pitești</h1><form className="mt-7 flex gap-2"><select className="field max-w-52" name="categorie" defaultValue={category}><option value="">Toate categoriile</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="button-secondary">Filtrează</button></form>{places?.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2">{places.map((place) => { const photoUrl = place.photo_path ? urlMap.get(place.photo_path) : undefined; return <article className="card overflow-hidden" key={place.id}>{photoUrl && <img src={photoUrl} alt="" className="aspect-[16/9] w-full object-cover" />}<div className="p-5"><span className="text-xs font-bold text-violet-300">{labels[place.category]}</span><h2 className="mt-2 text-xl font-bold">{place.name}</h2><p className="mt-1 text-sm text-fuchsia-200">{place.public_address}</p>{place.description && <p className="mt-3 text-sm leading-6 text-[#aaa4b8]">{place.description}</p>}</div></article>; })}</div> : <div className="card mt-7 p-10 text-center"><p className="text-2xl">◇</p><h2 className="mt-3 font-bold">Catalogul este pregătit</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#918a9e]">Locurile verificate vor fi adăugate din panoul de administrare în etapa următoare. Nu afișăm informații demonstrative ca fiind reale.</p></div>}</>;
}
